2019-06-06 10:37:23,918 log_Default_Display INFO   SSFERunHandler : Log initialised: Default_Display_Log
2019-06-06 10:37:45,904 log_Default_Display ERROR  object_SSFEFormMain : !!UNHAN_ERR!! ; Uncaught exception
Traceback (most recent call last):
  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\object_SSFEFormMain.py", line 7151, in func_QComboBox_SCENARIO_FILE_Selected
    self.func_Populate_Widgits_With_Config_Data__BATCH_SCENARIO(str_Batch_Scenario_Relative_Path_And_File__Current)
  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\object_SSFEFormMain.py", line 19091, in func_Populate_Widgits_With_Config_Data__BATCH_SCENARIO
    self.func_Get_Config_Data__BATCH_SCENARIO(self.obj_Config_Batch_Scenario)
  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\object_SSFEFormMain.py", line 22444, in func_Get_Config_Data__BATCH_SCENARIO
    bool_Success, self.int_Genome__Source_ALL_ALLELE_FREQUENCIES__Total_Loci, str_Message = self.func_Validate_Loci_From_File(str_Input_File_Path, str_Input_File_Name)
ValueError: need more than 2 values to unpack
