2017-05-19 15:46:05,007 log_Default_Display INFO   SSFERunHandler : Log initialised: Default_Display_Log
2017-05-19 15:46:05,063 log_Default_Display ERROR  object_SSFEFormMain : ; object_SSFEFormMain.py.func_Read_Config_File ;line: 23741 ; !!UNEXP_ERR!! ; Non-existant config file: 
  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\NOGP.py", line 568, in <module>
    func_Main(sys.argv[1:])

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\NOGP.py", line 553, in func_Main
    obj_SSRun.func_Run_Start()

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\SSFERunHandler.py", line 207, in func_Run_Start
    self.func_Run_Initiation()

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\SSFERunHandler.py", line 114, in func_Run_Initiation
    self.func_Run_Processing(obj_SSFEParams)

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\SSFERunHandler.py", line 184, in func_Run_Processing
    obj_GUI.func_Main()

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\SSFEGUIHandler.py", line 62, in func_Main
    , None)

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\object_SSFEFormMain.py", line 158, in __init__
    self.obj_Config_Settings = self.func_Read_Config_File(self.str_Application_Settings_Path_And_File, obj_Config)

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\object_SSFEFormMain.py", line 23741, in func_Read_Config_File
    self.func_Error_Handler__Caught_Exceptions(int_Stack_Trace_Level, str_Message_Text)

  File "Q:\CODE\NOG\v1_3_0_6_a1\devel\RS_SRC__NOG_v1_3_0_6_a1_devel\proj_Py2_NeOGenFE_v1_3_0_6_a1_devel\src\object_SSFEFormMain.py", line 23915, in func_Error_Handler__Caught_Exceptions
    stack = traceback.extract_stack()

